version: "3"
services:
  ricardobalk-website:
    build:
      context: .
      target: release
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
    command: ["nginx", "-g", "daemon off;"]