version: "3"
services:
  ricardobalk-website:
    build:
      context: .
      target: release
    ports:
      - 80:80
    environment:
      NODE_ENV: production
    command: ["nginx", "-g", "daemon off;"]